In [2]:
!/usr/bin/env python
# coding: utf-8

The system cannot find the path specified.


In [4]:
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
import sklearn
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import os
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from PIL import Image
import warnings
warnings.filterwarnings('ignore')
print(os.listdir("E:\ITI-Backup\Malaria Project"))


['.ipynb_checkpoints', 'archive (2)', 'archive (2).zip', 'Malaria Project.py', 'Untitled.ipynb']


In [5]:

path = "E:/ITI-Backup/Malaria Project/archive (2)/cell_images/"
path_data = os.listdir(path)
path_data
# now we will preprocesses our datatset

['Parasitized', 'Uninfected']

In [6]:
parasitized = os.listdir(path+path_data[0])
uninfected = os.listdir(path+path_data[1])

In [7]:
parasitized.remove("Thumbs.db")
uninfected.remove("Thumbs.db")


In [8]:
minh, minv = 100000, 100000
for p in parasitized:
    pic = Image.open(path+path_data[0]+"/"+p)
    if pic.size[0] < minh:
        minh = pic.size[0]
    if pic.size[1] < minv:
        minv = pic.size[1]
for u in uninfected:
    pic = Image.open(path+path_data[1]+"/"+u)
    if pic.size[0] < minh:
        minh = pic.size[0]
    if pic.size[1] < minv:
        minv = pic.size[1]
print(minh)
print(minv)


46
40


In [9]:

parasitized_list = []
for p in parasitized:
    image = Image.open(path+path_data[0]+"/"+p)
    image = image.resize((minh, minv))
    image = image.convert(mode="L")
    parasitized_list.append(image)
uninfected_list = []
for u in uninfected:
    image = Image.open(path+path_data[1]+"/"+u)
    image = image.resize((minh, minv))
    image = image.convert(mode="L")
    uninfected_list.append(image)

In [10]:
x = np.empty((len(uninfected)+len(parasitized), minh * minv))
index = 0
for pl in parasitized_list:
    x[index] = np.array(pl).reshape(minh * minv)
    index += 1
for ul in uninfected_list:
    x[index] = np.array(ul).reshape(minh * minv)
    index += 1
p = np.ones(len(parasitized))
u = np.zeros(len(uninfected))
y = np.concatenate((p, u), axis=0).reshape(x.shape[0], 1)

In [11]:

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=2)

In [12]:
# Feature Scaling

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


In [13]:
# NAIVE BAYES MODEL
naive = GaussianNB()
naive.fit(x, y)
y_pred = naive.predict(x_test)


print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(
    metrics.mean_squared_error(y_test, y_pred)))

[[   0 4129]
 [   0 4139]]
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00      4129
         1.0       0.50      1.00      0.67      4139

    accuracy                           0.50      8268
   macro avg       0.25      0.50      0.33      8268
weighted avg       0.25      0.50      0.33      8268

0.5006047411707789
Mean Absolute Error: 0.4993952588292211
Mean Squared Error: 0.4993952588292211
Root Mean Squared Error: 0.7066790352268992


In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=100)

In [16]:
# Feature Scaling

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [17]:

classifier = RandomForestClassifier(n_estimators=20, random_state=0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)


print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(
    metrics.mean_squared_error(y_test, y_pred)))

[[3222  831]
 [1047 3168]]
              precision    recall  f1-score   support

         0.0       0.75      0.79      0.77      4053
         1.0       0.79      0.75      0.77      4215

    accuracy                           0.77      8268
   macro avg       0.77      0.77      0.77      8268
weighted avg       0.77      0.77      0.77      8268

0.7728592162554426
Mean Absolute Error: 0.22714078374455732
Mean Squared Error: 0.22714078374455732
Root Mean Squared Error: 0.47659289099246677


In [18]:
classifier = RandomForestClassifier(n_estimators=150, random_state=2)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)



print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

[[3180  873]
 [ 739 3476]]
              precision    recall  f1-score   support

         0.0       0.81      0.78      0.80      4053
         1.0       0.80      0.82      0.81      4215

    accuracy                           0.81      8268
   macro avg       0.81      0.80      0.80      8268
weighted avg       0.81      0.81      0.80      8268

0.8050314465408805
Mean Absolute Error: 0.1949685534591195
Mean Squared Error: 0.1949685534591195
Root Mean Squared Error: 0.4415524356847321


In [19]:
estimator = [
    ('RF', RandomForestClassifier(n_estimators=20, random_state=42)),
    ('NB', GaussianNB())
]
clf = StackingClassifier(estimators=estimator,
                         final_estimator=LogisticRegression())
print("Ensemble Accuracy = ", clf.fit(x_train, y_train).score(x_test, y_test))

Ensemble Accuracy =  0.7847121432027092


In [21]:
kfold = model_selection.KFold(n_splits=3)
model = BaggingClassifier(base_estimator=classifier,
                          n_estimators=100)

results = model_selection.cross_val_score(model, x_test, y_test, cv=kfold)
print("Ensemble Accuracy = ", results.mean())


Ensemble Accuracy =  0.7581035316884374


In [22]:
kfold = model_selection.KFold(n_splits=3)
model = BaggingClassifier(base_estimator=classifier,
                          n_estimators=5)

results = model_selection.cross_val_score(model, x_test, y_test, cv=kfold)
print("Ensemble Accuracy = ", results.mean())

Ensemble Accuracy =  0.7594339622641509


In [23]:
kfold = model_selection.KFold(n_splits=3)
model = BaggingClassifier(base_estimator=naive,
                          n_estimators=50)

results = model_selection.cross_val_score(model, x_test, y_test, cv=kfold)
print("Ensemble Accuracy = ", results.mean())

Ensemble Accuracy =  0.6075229801644896


In [24]:
kfold = model_selection.KFold(n_splits=3)
model = BaggingClassifier(base_estimator=naive,
                          n_estimators=100)

results = model_selection.cross_val_score(model, x_test, y_test, cv=kfold)
print("Ensemble Accuracy = ", results.mean())

Ensemble Accuracy =  0.6081277213352685


In [25]:
clfs = [
    ('RF', RandomForestClassifier(n_estimators=10)),
    ('NB', GaussianNB())
]
voting_clf = VotingClassifier(clfs, voting='hard')
print("Ensemble Accuracy = ", voting_clf.fit(
    x_train, y_train).score(x_test, y_test))

Ensemble Accuracy =  0.6245766811804547
